## はじめに

実際のアプリケーションでは、予期できるものから予期できないものまで様々なエラーが起こります。Javascriptはシングルスレッドで動いているため、一度エラーが起こるとアプリケーション全体が止まってしまいます。そのため、エラーが起こった場合でも、適切に処理を行いプログラムが動き続けるようにする必要があります。Promiseオブジェクトの持つ、catch関数はこのエラー処理の仕組みの一つです。ここでは、こうしたエラー処理についてより詳しく見ていきましょう。

## strictモード

strictモードは、プログラムをブラウザがより厳しくチェックするモードです。ES5のコードでは`"use strict"`という文字がファイルの先頭やブロックの先頭に書かれていることがよくあります。これはstrictモードを適用したい場合の呼び出し文です。strictモードでは、通常モードではエラーが出ず、後々問題が発生しやすいような事柄に対してエラーを出します。

strictモード適用時にエラーが出るプログラムの例: 

```javascript
function test(test, test) {} // VM601:1 Uncaught SyntaxError: Identifier 'test' has already been declared
/* 
同じ名前の引数をファンクション定義で使っているため、シンタックスエラーが返ります。
*/
```

ES6のモジュールにはデフォルトでstrictモードが適用されるため、呼び出し文を書く必要はありません。ES5のプログラムを見ていて"use strict"の文字を見たら、このstrictモードを適用しているのだ、とだけ理解出来れば大丈夫です。詳しい違いを知りたい方はMDNの[ドキュメント](https://developer.mozilla.org/ja/docs/Web/JavaScript/Strict_mode)をご覧ください。
